const eraData = [
  {
    _id: 1,
    name: "Budding Years (30s-40s)",
    noOfSongs: 1300,
    noOfMovies: 103,
    liked: false,
  },
  {
    _id: 2,
    name: "Golden Era (50s-60s)",
    noOfSongs: 2300,
    noOfMovies: 604,
    liked: false,
  },
  {
    _id: 3,
    name: "New Age (70s-80s)",
    noOfSongs: 3200,
    noOfMovies: 890,
    liked: false,
  },
  {
    _id: 4,
    name: "Roaring 90s (90s-2000s)",
    noOfSongs: 4700,
    noOfMovies: 1045,
    liked: false,
  },
  {
    _id: 5,
    name: "Modern 20s (2010s-20s)",
    noOfSongs: 3590,
    noOfMovies: 904,
    liked: false,
  },
  {
    _id: 6,
    name: "Latest (2020s-ToDate)",
    noOfSongs: 1059,
    noOfMovies: 673,
    liked: false,
  },
];

const decadeData = [
  {
    _id: 1,
    name: "1930s",
    noOfSongs: 130,
    noOfMovies: 10,
    liked: false,
  },
  {
    _id: 2,
    name: "1940s",
    noOfSongs: 230,
    noOfMovies: 60,
    liked: false,
  },
  {
    _id: 3,
    name: "1950s",
    noOfSongs: 320,
    noOfMovies: 89,
    liked: false,
  },
  {
    _id: 4,
    name: "1960s",
    noOfSongs: 470,
    noOfMovies: 104,
    liked: false,
  },
  {
    _id: 5,
    name: "1970s",
    noOfSongs: 359,
    noOfMovies: 90,
    liked: false,
  },
  {
    _id: 6,
    name: "1980s",
    noOfSongs: 105,
    noOfMovies: 67,
    liked: false,
  },
  {
    _id: 7,
    name: "1990s",
    noOfSongs: 144,
    noOfMovies: 63,
    liked: false,
  },
  {
    _id: 8,
    name: "2000s",
    noOfSongs: 229,
    noOfMovies: 103,
    liked: false,
  },
  {
    _id: 9,
    name: "2010s",
    noOfSongs: 349,
    noOfMovies: 323,
    liked: false,
  },
  {
    _id: 10,
    name: "2020s",
    noOfSongs: 246,
    noOfMovies: 134,
    liked: false,
  },
];

const yearData = [
  {
    _id: "1",
    name: "1931",
    noOfSongs: "179",
    noOfMovies: "8",
    liked: false,
  },
  {
    _id: "2",
    name: "1932",
    noOfSongs: "279",
    noOfMovies: "10",
    liked: false,
  },
  {
    _id: "3",
    name: "1933",
    noOfSongs: "169",
    noOfMovies: "14",
    liked: false,
  },
  {
    _id: "4",
    name: "1934",
    noOfSongs: "674",
    noOfMovies: "12",
    liked: false,
  },
  {
    _id: "5",
    name: "1935",
    noOfSongs: "790",
    noOfMovies: "20",
    liked: false,
  },
  {
    _id: "6",
    name: "1936",
    noOfSongs: "957",
    noOfMovies: "0",
    liked: false,
  },
  {
    _id: "7",
    name: "1937",
    noOfSongs: "417",
    noOfMovies: "2",
    liked: false,
  },
  {
    _id: "8",
    name: "1938",
    noOfSongs: "975",
    noOfMovies: "16",
    liked: false,
  },
  {
    _id: "9",
    name: "1939",
    noOfSongs: "759",
    noOfMovies: "16",
    liked: false,
  },
  {
    _id: "10",
    name: "1940",
    noOfSongs: "23",
    noOfMovies: "14",
    liked: false,
  },
  {
    _id: "11",
    name: "1941",
    noOfSongs: "906",
    noOfMovies: "16",
    liked: false,
  },
  {
    _id: "12",
    name: "1942",
    noOfSongs: "76",
    noOfMovies: "16",
    liked: false,
  },
  {
    _id: "13",
    name: "1943",
    noOfSongs: "550",
    noOfMovies: "18",
    liked: false,
  },
  {
    _id: "14",
    name: "1944",
    noOfSongs: "59",
    noOfMovies: "16",
    liked: false,
  },
  {
    _id: "15",
    name: "1945",
    noOfSongs: "522",
    noOfMovies: "4",
    liked: false,
  },
  {
    _id: "16",
    name: "1946",
    noOfSongs: "454",
    noOfMovies: "10",
    liked: false,
  },
  {
    _id: "17",
    name: "1947",
    noOfSongs: "69",
    noOfMovies: "8",
    liked: false,
  },
  {
    _id: "18",
    name: "1948",
    noOfSongs: "769",
    noOfMovies: "4",
    liked: false,
  },
  {
    _id: "19",
    name: "1949",
    noOfSongs: "161",
    noOfMovies: "10",
    liked: false,
  },
  {
    _id: "20",
    name: "1950",
    noOfSongs: "197",
    noOfMovies: "0",
    liked: false,
  },
  {
    _id: "21",
    name: "1951",
    noOfSongs: "867",
    noOfMovies: "16",
    liked: false,
  },
  {
    _id: "22",
    name: "1952",
    noOfSongs: "418",
    noOfMovies: "12",
    liked: false,
  },
  {
    _id: "23",
    name: "1953",
    noOfSongs: "129",
    noOfMovies: "8",
    liked: false,
  },
  {
    _id: "24",
    name: "1954",
    noOfSongs: "770",
    noOfMovies: "8",
    liked: false,
  },
  {
    _id: "25",
    name: "1955",
    noOfSongs: "67",
    noOfMovies: "6",
    liked: false,
  },
  {
    _id: "26",
    name: "1956",
    noOfSongs: "282",
    noOfMovies: "2",
    liked: false,
  },
  {
    _id: "27",
    name: "1957",
    noOfSongs: "547",
    noOfMovies: "14",
    liked: false,
  },
  {
    _id: "28",
    name: "1958",
    noOfSongs: "491",
    noOfMovies: "10",
    liked: false,
  },
  {
    _id: "29",
    name: "1959",
    noOfSongs: "359",
    noOfMovies: "4",
    liked: false,
  },
  {
    _id: "30",
    name: "1960",
    noOfSongs: "779",
    noOfMovies: "14",
    liked: false,
  },
  {
    _id: "31",
    name: "1961",
    noOfSongs: "671",
    noOfMovies: "8",
    liked: false,
  },
  {
    _id: "32",
    name: "1962",
    noOfSongs: "107",
    noOfMovies: "2",
    liked: false,
  },
  {
    _id: "33",
    name: "1963",
    noOfSongs: "606",
    noOfMovies: "4",
    liked: false,
  },
  {
    _id: "34",
    name: "1964",
    noOfSongs: "246",
    noOfMovies: "14",
    liked: false,
  },
  {
    _id: "35",
    name: "1965",
    noOfSongs: "116",
    noOfMovies: "6",
    liked: false,
  },
  {
    _id: "36",
    name: "1966",
    noOfSongs: "481",
    noOfMovies: "18",
    liked: false,
  },
  {
    _id: "37",
    name: "1967",
    noOfSongs: "276",
    noOfMovies: "20",
    liked: false,
  },
  {
    _id: "38",
    name: "1968",
    noOfSongs: "766",
    noOfMovies: "6",
    liked: false,
  },
  {
    _id: "39",
    name: "1969",
    noOfSongs: "364",
    noOfMovies: "6",
    liked: false,
  },
  {
    _id: "40",
    name: "1970",
    noOfSongs: "406",
    noOfMovies: "12",
    liked: false,
  },
  {
    _id: "41",
    name: "1971",
    noOfSongs: "643",
    noOfMovies: "0",
    liked: false,
  },
  {
    _id: "42",
    name: "1972",
    noOfSongs: "40",
    noOfMovies: "10",
    liked: false,
  },
  {
    _id: "43",
    name: "1973",
    noOfSongs: "177",
    noOfMovies: "14",
    liked: false,
  },
  {
    _id: "44",
    name: "1974",
    noOfSongs: "759",
    noOfMovies: "18",
    liked: false,
  },
  {
    _id: "45",
    name: "1975",
    noOfSongs: "792",
    noOfMovies: "4",
    liked: false,
  },
  {
    _id: "46",
    name: "1976",
    noOfSongs: "310",
    noOfMovies: "12",
    liked: false,
  },
  {
    _id: "47",
    name: "1977",
    noOfSongs: "56",
    noOfMovies: "12",
    liked: false,
  },
  {
    _id: "48",
    name: "1978",
    noOfSongs: "54",
    noOfMovies: "8",
    liked: false,
  },
  {
    _id: "49",
    name: "1979",
    noOfSongs: "697",
    noOfMovies: "4",
    liked: false,
  },
  {
    _id: "50",
    name: "1980",
    noOfSongs: "130",
    noOfMovies: "10",
    liked: false,
  },
  {
    _id: "51",
    name: "1981",
    noOfSongs: "683",
    noOfMovies: "18",
    liked: false,
  },
  {
    _id: "52",
    name: "1982",
    noOfSongs: "418",
    noOfMovies: "8",
    liked: false,
  },
  {
    _id: "53",
    name: "1983",
    noOfSongs: "731",
    noOfMovies: "6",
    liked: false,
  },
  {
    _id: "54",
    name: "1984",
    noOfSongs: "688",
    noOfMovies: "12",
    liked: false,
  },
  {
    _id: "55",
    name: "1985",
    noOfSongs: "181",
    noOfMovies: "4",
    liked: false,
  },
  {
    _id: "56",
    name: "1986",
    noOfSongs: "686",
    noOfMovies: "8",
    liked: false,
  },
  {
    _id: "57",
    name: "1987",
    noOfSongs: "237",
    noOfMovies: "10",
    liked: false,
  },
  {
    _id: "58",
    name: "1988",
    noOfSongs: "992",
    noOfMovies: "6",
    liked: false,
  },
  {
    _id: "59",
    name: "1989",
    noOfSongs: "110",
    noOfMovies: "14",
    liked: false,
  },
  {
    _id: "60",
    name: "1990",
    noOfSongs: "97",
    noOfMovies: "6",
    liked: false,
  },
  {
    _id: "61",
    name: "1991",
    noOfSongs: "90",
    noOfMovies: "12",
    liked: false,
  },
  {
    _id: "62",
    name: "1992",
    noOfSongs: "125",
    noOfMovies: "10",
    liked: false,
  },
  {
    _id: "63",
    name: "1993",
    noOfSongs: "732",
    noOfMovies: "8",
    liked: false,
  },
  {
    _id: "64",
    name: "1994",
    noOfSongs: "848",
    noOfMovies: "18",
    liked: false,
  },
  {
    _id: "65",
    name: "1995",
    noOfSongs: "604",
    noOfMovies: "10",
    liked: false,
  },
  {
    _id: "66",
    name: "1996",
    noOfSongs: "965",
    noOfMovies: "16",
    liked: false,
  },
  {
    _id: "67",
    name: "1997",
    noOfSongs: "111",
    noOfMovies: "12",
    liked: false,
  },
  {
    _id: "68",
    name: "1998",
    noOfSongs: "614",
    noOfMovies: "12",
    liked: false,
  },
  {
    _id: "69",
    name: "1999",
    noOfSongs: "279",
    noOfMovies: "6",
    liked: false,
  },
  {
    _id: "70",
    name: "2000",
    noOfSongs: "56",
    noOfMovies: "6",
    liked: false,
  },
  {
    _id: "71",
    name: "2001",
    noOfSongs: "480",
    noOfMovies: "6",
    liked: false,
  },
  {
    _id: "72",
    name: "2002",
    noOfSongs: "443",
    noOfMovies: "10",
    liked: false,
  },
  {
    _id: "73",
    name: "2003",
    noOfSongs: "599",
    noOfMovies: "18",
    liked: false,
  },
  {
    _id: "74",
    name: "2004",
    noOfSongs: "971",
    noOfMovies: "2",
    liked: false,
  },
  {
    _id: "75",
    name: "2005",
    noOfSongs: "154",
    noOfMovies: "2",
    liked: false,
  },
  {
    _id: "76",
    name: "2006",
    noOfSongs: "686",
    noOfMovies: "18",
    liked: false,
  },
  {
    _id: "77",
    name: "2007",
    noOfSongs: "334",
    noOfMovies: "20",
    liked: false,
  },
  {
    _id: "78",
    name: "2008",
    noOfSongs: "850",
    noOfMovies: "0",
    liked: false,
  },
  {
    _id: "79",
    name: "2009",
    noOfSongs: "892",
    noOfMovies: "20",
    liked: false,
  },
  {
    _id: "80",
    name: "2010",
    noOfSongs: "956",
    noOfMovies: "10",
    liked: false,
  },
  {
    _id: "81",
    name: "2011",
    noOfSongs: "804",
    noOfMovies: "2",
    liked: false,
  },
  {
    _id: "82",
    name: "2012",
    noOfSongs: "925",
    noOfMovies: "2",
    liked: false,
  },
  {
    _id: "83",
    name: "2013",
    noOfSongs: "231",
    noOfMovies: "18",
    liked: false,
  },
  {
    _id: "84",
    name: "2014",
    noOfSongs: "454",
    noOfMovies: "10",
    liked: false,
  },
  {
    _id: "85",
    name: "2015",
    noOfSongs: "865",
    noOfMovies: "0",
    liked: false,
  },
  {
    _id: "86",
    name: "2016",
    noOfSongs: "353",
    noOfMovies: "12",
    liked: false,
  },
  {
    _id: "87",
    name: "2017",
    noOfSongs: "794",
    noOfMovies: "14",
    liked: false,
  },
  {
    _id: "88",
    name: "2018",
    noOfSongs: "275",
    noOfMovies: "12",
    liked: false,
  },
  {
    _id: "89",
    name: "2019",
    noOfSongs: "96",
    noOfMovies: "14",
    liked: false,
  },
  {
    _id: "90",
    name: "2020",
    noOfSongs: "687",
    noOfMovies: "8",
    liked: false,
  },
  {
    _id: "91",
    name: "2021",
    noOfSongs: "216",
    noOfMovies: "6",
    liked: false,
  },
  {
    _id: "92",
    name: "2022",
    noOfSongs: "153",
    noOfMovies: "10",
    liked: false,
  },
];

const movies = [
  {
    id: 2,
    title: "Alam Ara",
    year: "",
    cast: [
      "Master Vithal",
      "Vithal Zubeida",
      "Susheela",
      "Jillo",
      "Prithviraj Kapoor",
      "V M Khan",
      "Elizer",
      "Jagdish Sethi",
      "T L V Prasad",
    ],
    singers: ["Firozshah Mistry", "B Irani"],
    lyricists: [],
    musicdirectors: [],
    moviedirectors: [],
    movieproducers: [],
    imdblinks: [],
    wikilinks: [],
    videoyoutubelinks: [],
  },
  {
    id: 174,
    title: "Prem Kahani",
    year: "1937",
    cast: [
      "Ashok Kumar",
      "N.M. Joshi",
      "Mayadevi",
      "Vimala Devi",
      "Madhurika Devi",
    ],
    singers: [
      "Ashok Kumar",
      "Saraswati Devi",
      "Sunita Devi",
      "Mumtaz Ali",
      "Maya Devi",
    ],
    lyricists: ["Jamuna Swaroop Kashyap Naatwan"],
    musicdirectors: ["Saraswati Devi"],
    moviedirectors: ["Franz Osten"],
    movieproducers: ["Himanshu Rai"],
    imdblinks: ["prem_kahani_1937.htm"],
    wikilinks: ["https://en.wikipedia.org/wiki/Prem_Kahani_(1937_film)"],
    videoyoutubelinks: ["CmegqkzyMo0", "fzsowvBLoqo"],
  },
  {
    id: 275,
    title: "Padosi",
    year: "1941",
    cast: [
      "Mazhar Khan",
      "Gajanan Jagirdar",
      "Anees Khatoon",
      "Radha Kishan",
      "Lajwanti",
      "Sumitra",
      "Gopal",
      "Balak Ram",
    ],
    singers: ["Anees Khatoon", "Balwant Singh", "Balakram", "Gopal"],
    lyricists: ["Pandit Sudarshan"],
    musicdirectors: ["Master Krishnarao"],
    moviedirectors: ["V Shantaram"],
    movieproducers: ["Prabhat"],
    imdblinks: ["tt0331308"],
    wikilinks: ["Padosi"],
    videoyoutubelinks: ["w1xv45wdNiI"],
  },
];

export function getData(params, selectedParam) {
  if (!selectedParam) {
    return [];
  } else {
    if (selectedParam === "Era") {
      return eraData;
    } else if (selectedParam === "Decade") {
      return decadeData;
    } else if (selectedParam === "Year") {
      return yearData;
    } else return [];
  }
}

export function getMovies() {
  return movies;
}

export function getSong(id) {
  return null;
}
